-- SIDEP-CE - Banco de Questões v2
-- Componente: INFORMÁTICA BÁSICA
-- Competência: C-IB
-- Descritor: IB-D01
-- Descritor avaliável: Distinguir tecnologia, computação, informática, hardware e software em situações cotidianas.
-- Lote: 20 questões fáceis, contextualizadas, em revisão docente.

insert into questao_mvp (
  codigo,
  descritor_codigo,
  componente_curricular,
  enunciado,
  alternativa_a,
  alternativa_b,
  alternativa_c,
  alternativa_d,
  alternativa_e,
  gabarito,
  justificativa,
  imagem_url,
  dificuldade_inicial,
  status,
  atualizada_em
) values
(
  'Q-INF-0001',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$Em uma aula prática, o professor pede que os estudantes identifiquem o que pode ser tocado fisicamente no computador. Um aluno aponta o teclado, o monitor e o mouse. Esses itens são exemplos de:$$,
  $$software, pois executam programas no computador.$$,
  $$hardware, pois são partes físicas do computador.$$,
  $$informática, pois representam uma área de estudo.$$,
  $$computação, pois resolvem problemas matemáticos.$$,
  $$tecnologia, pois são apenas ideias de inovação.$$,
  'B',
  $$Hardware é o conjunto de partes físicas de um computador, como teclado, monitor, mouse, gabinete e impressora.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0002',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$Na secretaria de uma escola, a funcionária usa um editor de texto para escrever uma declaração. O computador, o teclado e a impressora são equipamentos físicos; já o editor de texto é um:$$,
  $$software, porque é um programa usado para realizar uma tarefa.$$,
  $$hardware, porque pode ser segurado com as mãos.$$,
  $$cabo de rede, porque conecta computadores.$$,
  $$periférico, porque substitui o teclado.$$,
  $$monitor, porque exibe as informações na tela.$$,
  'A',
  $$Software é o programa ou conjunto de instruções que orienta o computador a executar tarefas, como editar texto, navegar na internet ou calcular valores.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0003',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$Uma equipe de estudantes cria uma planilha para organizar os gastos de uma feira escolar. Eles usam fórmulas para somar valores e gerar resultados automaticamente. Nesse caso, o uso do computador para organizar e processar informações se relaciona mais diretamente à:$$,
  $$decoração da sala de aula.$$,
  $$informática, pois envolve uso de recursos computacionais para tratar informação.$$,
  $$manutenção elétrica, pois depende de energia na tomada.$$,
  $$troca de peças do computador.$$,
  $$limpeza física dos equipamentos.$$,
  'B',
  $$Informática envolve o uso de computadores, programas e recursos digitais para produzir, armazenar, processar e comunicar informações.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0004',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$Um estudante diz: "Meu celular, minha geladeira frost free e o sistema de irrigação automática da escola são tecnologias, mesmo que nem todos sejam computadores". A afirmação está correta porque tecnologia é:$$,
  $$somente um computador de mesa conectado à internet.$$,
  $$qualquer solução criada para atender necessidades humanas ou resolver problemas.$$,
  $$apenas um programa instalado no celular.$$,
  $$somente uma peça física interna do gabinete.$$,
  $$qualquer texto digitado em um editor.$$,
  'B',
  $$Tecnologia é um conjunto de conhecimentos, técnicas, ferramentas ou soluções criadas para resolver problemas e melhorar atividades humanas.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0005',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$Durante uma atividade, a professora explica que a computação estuda formas de representar problemas e criar soluções usando algoritmos e processamento de dados. Qual situação melhor representa essa ideia?$$,
  $$Escolher a cor da capa de um caderno sem nenhum critério.$$,
  $$Criar uma sequência de passos para calcular automaticamente a média dos alunos.$$,
  $$Limpar a tela do monitor com pano seco.$$,
  $$Ligar a lâmpada da sala manualmente.$$,
  $$Guardar o teclado dentro de uma caixa.$$,
  'B',
  $$Computação envolve raciocínio, algoritmos, dados e processos para resolver problemas de forma estruturada, muitas vezes com apoio de computadores.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0006',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$Em um laboratório, o computador liga normalmente, mas o navegador não abre porque o programa foi removido. O problema descrito está mais relacionado a:$$,
  $$hardware, pois o monitor quebrou.$$,
  $$software, pois envolve um programa instalado no sistema.$$,
  $$energia elétrica, pois o computador não liga.$$,
  $$mobiliário, pois a mesa está inadequada.$$,
  $$cabos, pois todos os programas ficam nos cabos.$$,
  'B',
  $$Se o equipamento físico funciona, mas um programa não abre ou foi removido, o problema está ligado ao software.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0007',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$Uma professora quer exibir um vídeo educativo, mas percebe que o cabo HDMI está danificado. Mesmo com o programa funcionando, a imagem não chega ao projetor. O cabo HDMI, nesse contexto, é um exemplo de:$$,
  $$software de apresentação.$$,
  $$hardware, pois é um componente físico usado na conexão.$$,
  $$arquivo digital, pois contém o vídeo.$$,
  $$algoritmo, pois calcula a imagem.$$,
  $$sistema operacional, pois controla o computador inteiro.$$,
  'B',
  $$Cabos, conectores e periféricos são componentes físicos, portanto fazem parte do hardware.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0008',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$Um estudante afirma que "software é tudo aquilo que aparece na tela e ajuda o usuário a realizar uma tarefa, como um aplicativo de mensagens, um jogo ou um navegador". Qual exemplo abaixo é software?$$,
  $$Mouse.$$,
  $$Impressora.$$,
  $$Navegador de internet.$$,
  $$Teclado.$$,
  $$Cabo de energia.$$,
  'C',
  $$Navegador de internet é um programa usado para acessar páginas e serviços online; por isso, é software.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0009',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$Na cantina da escola, a equipe usa uma maquininha de pagamento por aproximação. Essa solução utiliza conhecimentos e dispositivos para facilitar uma necessidade cotidiana. O melhor conceito para essa solução é:$$,
  $$tecnologia.$$,
  $$apagador.$$,
  $$cadeira.$$,
  $$papel rascunho.$$,
  $$giz de quadro.$$,
  'A',
  $$A maquininha é uma tecnologia porque combina conhecimentos, dispositivos e procedimentos para resolver a necessidade de pagamento.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0010',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$Um aluno está montando um computador e separa processador, memória RAM, placa-mãe e fonte. Antes de instalar qualquer programa, ele está trabalhando principalmente com:$$,
  $$arquivos de texto.$$,
  $$hardware.$$,
  $$redes sociais.$$,
  $$planilhas online.$$,
  $$senhas de usuário.$$,
  'B',
  $$Processador, memória RAM, placa-mãe e fonte são componentes físicos do computador, portanto pertencem ao hardware.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0011',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$Uma estudante instala um aplicativo para estudar inglês no celular. O celular é o equipamento físico, mas o aplicativo que apresenta exercícios, sons e pontuação é classificado como:$$,
  $$hardware.$$,
  $$software.$$,
  $$tomada.$$,
  $$gabinete.$$,
  $$monitor externo.$$,
  'B',
  $$Aplicativos são softwares, pois são programas que executam funções específicas em dispositivos digitais.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0012',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$No projeto de robótica da escola, os alunos escrevem uma sequência de comandos para que o robô avance, pare e vire. Essa sequência de passos se aproxima mais do conceito de:$$,
  $$algoritmo dentro do campo da computação.$$,
  $$parafuso do gabinete.$$,
  $$folha impressa sem instrução.$$,
  $$cadeira de laboratório.$$,
  $$cabo de energia sem uso.$$,
  'A',
  $$Um algoritmo é uma sequência organizada de passos para resolver um problema ou realizar uma tarefa, conceito central da computação.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0013',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$A escola recebeu novos notebooks. Para funcionarem, eles precisam tanto das partes físicas quanto dos programas. Qual alternativa apresenta corretamente um exemplo de hardware e um exemplo de software?$$,
  $$Teclado e editor de texto.$$,
  $$Navegador e planilha.$$,
  $$Mouse e teclado.$$,
  $$Sistema operacional e aplicativo.$$,
  $$Arquivo e pasta digital.$$,
  'A',
  $$Teclado é hardware, pois é físico; editor de texto é software, pois é um programa usado para escrever e formatar documentos.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0014',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$Um estudante diz que "computação e informática são a mesma coisa". A professora explica que elas se relacionam, mas não são exatamente iguais. Qual explicação é mais adequada?$$,
  $$Computação estuda apenas tomada elétrica, e informática estuda apenas cadeiras.$$,
  $$Computação trata de fundamentos, algoritmos e processamento; informática usa recursos computacionais para lidar com informação.$$,
  $$Informática é apenas limpar o teclado, e computação é apenas imprimir textos.$$,
  $$Computação é sempre manual, e informática nunca usa computadores.$$,
  $$As duas palavras significam somente redes sociais.$$,
  'B',
  $$Computação está ligada a fundamentos e resolução de problemas por algoritmos e processamento; informática aplica recursos computacionais ao tratamento da informação.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0015',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$Em uma loja, o atendente usa um sistema para registrar produtos, calcular o total da compra e emitir recibo. O sistema instalado no computador é:$$,
  $$um software.$$,
  $$um mouse.$$,
  $$uma gaveta física.$$,
  $$um cabo USB.$$,
  $$um monitor desligado.$$,
  'A',
  $$O sistema de vendas é um programa que executa tarefas de registro e cálculo, portanto é software.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0016',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$Ao comparar objetos da sala, um aluno separa lousa digital, projetor e notebook como recursos criados para apoiar o ensino. Mesmo tendo formatos diferentes, todos podem ser entendidos como:$$,
  $$tecnologias educacionais.$$,
  $$somente softwares.$$,
  $$somente arquivos digitais.$$,
  $$apenas algoritmos.$$,
  $$apenas sistemas operacionais.$$,
  'A',
  $$Tecnologias educacionais são soluções, equipamentos ou recursos criados para apoiar processos de ensino e aprendizagem.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0017',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$Um computador apresenta tela quebrada, mas o sistema operacional e os programas continuam instalados. O problema principal está no:$$,
  $$hardware, pois a tela é uma parte física do equipamento.$$,
  $$software, pois a tela é um aplicativo.$$,
  $$arquivo, pois a tela guarda documentos.$$,
  $$site, pois todo monitor é uma página da internet.$$,
  $$algoritmo, pois a tela é uma sequência de passos.$$,
  'A',
  $$A tela é um componente físico. Quando ela quebra, o problema principal está relacionado ao hardware.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0018',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$Na aula, a turma discute que um aplicativo de mapas calcula rotas, estima tempo de chegada e orienta o caminho. Essa situação combina tecnologia e computação porque:$$,
  $$usa dados e processamento para resolver um problema prático de localização.$$,
  $$funciona apenas como enfeite na tela do celular.$$,
  $$não depende de nenhuma instrução ou processamento.$$,
  $$é formado somente por parafusos e cabos.$$,
  $$serve apenas para aumentar o brilho da tela.$$,
  'A',
  $$O aplicativo processa dados e executa instruções para resolver um problema prático, que é encontrar rotas e orientar deslocamentos.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0019',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$Um aluno salva um arquivo de apresentação no computador. Depois, usa um projetor para apresentar o trabalho. Considerando os conceitos básicos, o arquivo e o programa usado para abrir a apresentação são exemplos de:$$,
  $$software e dados digitais.$$,
  $$peças metálicas do gabinete.$$,
  $$periféricos físicos de entrada.$$,
  $$cabos de energia.$$,
  $$parafusos do monitor.$$,
  'A',
  $$Arquivos são dados digitais, e o programa que os abre é software. Eles não são partes físicas como cabos, monitor ou teclado.$$,
  null,
  1.00,
  'em_revisao',
  now()
),
(
  'Q-INF-0020',
  'IB-D01',
  'INFORMÁTICA BÁSICA',
  $$Uma escola quer ensinar segurança digital. Antes disso, o professor pergunta: "Qual diferença básica entre hardware e software vocês precisam entender?". A resposta mais correta é:$$,
  $$hardware é a parte física do dispositivo; software são os programas e instruções que funcionam nele.$$,
  $$hardware é sempre gratuito; software é sempre pago.$$,
  $$hardware só existe na internet; software só existe em papel.$$,
  $$hardware é uma senha; software é uma mesa.$$,
  $$hardware e software são nomes diferentes para a mesma coisa.$$,
  'A',
  $$A distinção fundamental é que hardware corresponde aos componentes físicos, enquanto software corresponde aos programas e instruções executados pelo dispositivo.$$,
  null,
  1.00,
  'em_revisao',
  now()
)
on conflict (codigo) do update set
  descritor_codigo = excluded.descritor_codigo,
  componente_curricular = excluded.componente_curricular,
  enunciado = excluded.enunciado,
  alternativa_a = excluded.alternativa_a,
  alternativa_b = excluded.alternativa_b,
  alternativa_c = excluded.alternativa_c,
  alternativa_d = excluded.alternativa_d,
  alternativa_e = excluded.alternativa_e,
  gabarito = excluded.gabarito,
  justificativa = excluded.justificativa,
  imagem_url = excluded.imagem_url,
  dificuldade_inicial = excluded.dificuldade_inicial,
  status = excluded.status,
  atualizada_em = now();

select descritor_codigo, status, count(*)::int as total
from questao_mvp
where descritor_codigo = 'IB-D01'
group by descritor_codigo, status
order by status;
